<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="intl.i18n_test.CountryNameTest-20160305004443" tests="2" time="0.070">
	<testcase classname="intl.i18n_test.CountryNameTest" name="test_country_name_for_english_request" time="0.044">
		<error message="False is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Users/jlfwong/khan/webapp/intl/i18n_test.py", line 214, in test_country_name_for_english_request
    self.assert_country('ca', 'Canada')
  File "/Users/jlfwong/khan/webapp/intl/i18n_test.py", line 208, in assert_country
    self.assertTrue(False)
AssertionError: False is not true
]]>		</error>
	</testcase>
	<testcase classname="intl.i18n_test.CountryNameTest" name="test_country_name_for_french_request" time="0.025">
		<error message="False is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Users/jlfwong/khan/webapp/intl/i18n_test.py", line 219, in test_country_name_for_french_request
    self.assert_country('ca', 'Canada')
  File "/Users/jlfwong/khan/webapp/intl/i18n_test.py", line 208, in assert_country
    self.assertTrue(False)
AssertionError: False is not true
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
